# Site settings
title: Mario Jayakumar
description: 'University of Maryland, Computer Science'
url: '//mariojayakumar.com'
#baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Mario Jayakumar'
  email: mariojay@terpmail.umd.edu
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  MarioJayakumar
  linkedin_username:  mario-jayakumar

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
